yalla-coop/chiltern-music-therapy

client/src/components/Button/Button.stories.js, client/src/components/Button/index.js, client/src/components/Button/style.js, client/src/components/Modal/Modal.stories.js, client/src/components/Modal/index.js, client/src/components/Modal/style.js, client/src/helpers/set-margin.js, client/src/theme/index.js
Closes #40 
=======
---
---
---
- Project runs
- Code is consistent with …
=> 40 > Create Modal

client/src/components/Grid/style.js, client/src/theme/index.js
=======
---
---
---
- Project runs …
=> fix grid gutters

client/src/helpers/set-margin.js
=======
---
---
---
- Project runs …
=> fix set margins helper

client/src/App.js, client/src/components/GoBack/index.js, client/src/components/Inputs/BasicInput/index.js, client/src/components/Typography/index.js, client/src/constants/nav-routes.js, client/src/context/auth.js, client/src/pages/Therapist/Signup/index.js, client/src/pages/Therapist/Signup/style.js, client/src/pages/Therapist/index.js, client/src/validation/create-schema.js, client/src/validation/err-msgs.js, client/src/validation/fields.js, client/src/validation/index.js, client/src/validation/schemas/index.js, client/src/validation/schemas/login.js, client/src/validation/schemas/signup.js, client/src/validation/validate.js, server/modules/user/controllers/signup.js, server/modules/user/model/create.js, server/modules/user/use-cases/therapist-signup.js, server/modules/user/utils/validate-signup.js, server/services/error-handler/messages.js, server/services/validation/fields.js, server/services/validation/validate.js
#44 
=======
---
---
---
- Project runs …
=> 44 therapist sign up

client/src/App.js, client/src/components/Layout/General/index.js, client/src/components/Layout/General/style.js, client/src/components/Layout/Onboarding/index.js, client/src/components/Navbar/NavRoutes.js, client/src/components/Navbar/Navbar.stories.js, client/src/components/Navbar/index.js, client/src/components/Navbar/style.js, client/src/constants/nav-routes.js, client/src/constants/roles.js
#36 
=======
---
---
---
- Project runs …
=> 36 create navbar and menu

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Navbar/NavRoutes.js, client/src/constants/nav-routes.js, client/src/context/auth.js, client/src/pages/General/Login/index.js, client/src/pages/General/Login/style.js, client/src/pages/General/index.js, server/api/middlewares/authenticate.js, server/api/middlewares/authorize.js, server/config/server.js, server/constants/common.js, server/database/build.js, server/database/init/add-refs.sql, server/database/init/index.js, server/database/models/media/schema.sql, server/helpers/create-test-token.js, server/helpers/create-token.js, server/modules/user/model/create.js, server/modules/user/model/find.js
#46
=======
---
---
---
- Project runs …
=> 46 login / logout

client/src/App.js, client/src/api-calls/programmes.js, client/src/components/Cards/Link/index.js, client/src/components/Cards/Link/style.js, client/src/components/Layout/General/style.js, client/src/components/Title/Title.stories.js, client/src/components/Title/index.js, client/src/components/Typography/index.js, client/src/constants/nav-routes.js, client/src/pages/Client/AllProgrammes/index.js, client/src/pages/Client/AllProgrammes/style.js, client/src/pages/Client/index.js, client/src/theme/index.js, server/modules/programme/controllers/get-programmes-by-client.js, server/modules/programme/controllers/index.js, server/modules/programme/model/find.js, server/modules/programme/use-cases/get-programmes-by-client.js, server/modules/programme/use-cases/index.js
Closes #59 
=======
---
---
---
- Project runs
- Code is consistent with …
=> 59 > My Programmes

client/src/components/Avatar/index.js, client/src/components/Avatar/style.js
=======
---
---
---
- Project runs …
=> fix avatar component

client/src/App.js, client/src/api-calls/therapists-clients.js, client/src/components/Cards/Link/index.js, client/src/constants/nav-routes.js, client/src/helpers/cleanEmail.js, client/src/helpers/index.js, client/src/pages/Therapist/Profile/index.js, client/src/pages/Therapist/index.js, client/src/validation/custom-functions.js, client/src/validation/err-msgs.js, client/src/validation/fields.js, client/src/validation/schemas/index.js, client/src/validation/schemas/profile.js
#47 
=======
---
---
---
- Project runs …
=> 47 therapist can add profile(front end)

client/src/components/Inputs/Dropdown/index.js, client/src/components/Inputs/Inputs.stories.js
Updates dropdown so if you feed in a addNew prop it allows the user to add options now in the list
=======
---
---
---
- Project runs
- The new work has been checked with Axe accessibility …
=> Add option to add new

client/src/api-calls/programmes.js, client/src/pages/Client/AllProgrammes/index.js, client/src/pages/Client/Dashboard/index.js
#128 
=======
---
---
---
- Project runs …
=> fix issue on home programme passing user id

client/src/components/Inputs/Dropdown/index.js, client/src/pages/Client/IndividProgramme/index.js, client/src/pages/Therapist/IndividProgramme/index.js, server/modules/content/model/find.js, server/modules/programme/model/find.js
#69 
=======
---
---
---
- Project runs …
=> 69 > View Programme as Therapist (BACK)

client/src/api-calls/contents.js, client/src/components/Modal/index.js, client/src/pages/Therapist/Library/index.js, client/src/validation/schemas/editContent.js, client/src/validation/schemas/index.js, server/modules/content/controllers/delete-content.js, server/modules/content/controllers/edit-content.js, server/modules/content/controllers/index.js, server/modules/content/controllers/remove-content-from-library.js, server/modules/content/model/create.js, server/modules/content/model/find.js, server/modules/content/model/remove.js, server/modules/content/model/update.js, server/modules/content/use-cases/delete-content.js, server/modules/content/use-cases/edit-content.js, server/modules/content/use-cases/index.js, server/modules/content/use-cases/remove-content-from-library.js, server/services/error-handler/messages.js, server/services/events/event-types.js, server/services/events/media.js
#68 
**NOTE:**
At the moment if the user removes a category we remove that link from the content, but we do not remove the category completely from the categories table - to do that introduces lots of extra complexity to check where else that category is used etc. Considering the category table is literally two fields of data and is very low memory, I suggest this approach is fine for now and we can look to refactor in future for storage optimisation. 
=======
---
---
---
Please make sure you ensure the following has been done before marking your PR as awaiting-review. For full checklist …
=> 68 > Edit & Remove Content in Library

.vscode/settings.json, client/package-lock.json, client/package.json, client/src/components/Video/Video.stories.js, client/src/components/Video/index.js, client/src/theme/global-style.js
#35 
=======
to test: 
go to `server/services/files-storage/get-file-pre-signed-url.js` and add this at the end of the file
```js
console.log(getFilePreSignedUrl({
key:
'4/audio/mpeg-c4656ff5-ecfa-46de-9b0f-d3133c850ca3-Woodkid - Run Boy Run (1).mp3',
bucket: 'chilternmusictherapy',
}));
```
note:
- Project runs
- …
=> 35 media streaming

client/src/components/Cards/Expandable/EditMode.js, client/src/components/Cards/Expandable/ViewMode.js, client/src/components/Cards/Expandable/index.js, client/src/components/Video/index.js, client/src/pages/Client/IndividProgramme/index.js, client/src/pages/Therapist/AddClient/Step1.js, client/src/pages/Therapist/AddClient/Step2.js, client/src/pages/Therapist/AddClient/Step3.js, client/src/pages/Therapist/AddClient/Step4.js, client/src/pages/Therapist/CreateProgram/ReviewFinish.js, client/src/pages/Therapist/IndividProgramme/index.js, client/src/pages/Therapist/Library/index.js, client/src/theme/global-style.js, server/database/dummy-data/contents-content-categories.js, server/database/dummy-data/contents.js, server/database/dummy-data/media.js, server/database/dummy-data/programmes-contents.js, server/modules/content/model/find.js, server/modules/content/use-cases/get-content-by-prog.js, server/modules/content/use-cases/get-library-content.js, server/modules/content/utils/index.js, server/modules/content/utils/set-contents-media-file-url.js, server/services/files-storage/delete-file.js
#142 
=======
---
---
---
- Project runs …
=> documents download and content

client/src/components/Cards/Expandable/style.js, client/src/components/Cards/Link/style.js, client/src/components/FileUpload/style.js, client/src/components/Title/index.js, client/src/pages/Client/Dashboard/index.js, client/src/pages/Client/IndividProgramme/FeedbackSection.js, client/src/pages/Client/IndividProgramme/UpdateSection.js, client/src/pages/Client/IndividProgramme/index.js
Fixes #148 
Fixes #143 
Fixes #119 
=======
---
---
---
- Project runs
- …
=> Fix Style bugs

client/src/App.js, client/src/components/Route/index.js
#146 
=======
---
---
---
- Project runs …
=> 146 front end routing

client/src/components/Navbar/NavRoutes.js
#153 
=======
---
---
---
- Project runs …
=> fix the navbar style

client/src/pages/Therapist/MyAccount/index.js
#152 
=======
---
---
---
- Project runs …
=> Render account image

client/src/pages/Client/AllProgrammes/index.js, client/src/pages/Therapist/EditProgramme/Review.js, server/modules/programme/model/find.js, server/modules/therapist-client/model/find.js
#162 
=======
---
---
---
- Project runs …
=> 162 programmes order

client/src/pages/Therapist/MyAccount/index.js, client/src/pages/Therapist/Profile/index.js, server/modules/media/use-cases/get-media-url.js
#152 
=======
---
---
---
- Project runs …
=> 152 protect media url

client/src/App.js, client/src/api-calls/programmes.js, client/src/api-calls/progress-updates.js, client/src/constants/nav-routes.js, client/src/pages/Client/Feedback/Q1.js, client/src/pages/Client/Feedback/Q2.js, client/src/pages/Client/Feedback/Q3.js, client/src/pages/Client/Feedback/Q4.js, client/src/pages/Client/Feedback/index.js, client/src/pages/Client/index.js, client/src/pages/General/SuccessFeedback/index.js, client/src/pages/General/index.js, client/src/validation/fields.js, client/src/validation/schemas/feedback.js, client/src/validation/schemas/index.js
#78 
=======
---
---
---
- Project runs …
=> 78 send feedback frontend

client/src/pages/Client/MyTherapist/index.js, client/src/pages/Therapist/AddClient/Step4.js, client/src/pages/Therapist/Dashboard/index.js, client/src/pages/Therapist/MyAccount/index.js, client/src/pages/Therapist/Profile/index.js, client/src/pages/Therapist/SingleClient/ClientHistory.js, client/src/pages/Therapist/SingleClient/index.js, client/src/pages/Therapist/ViewUpdate/DocumentUpdate.js, client/src/pages/Therapist/ViewUpdate/VideoUpdate.js, client/src/pages/Therapist/ViewUpdate/index.js, server/helpers/set-media-file-url.js, server/modules/user/model/find.js, server/modules/user/use-cases/get-account-info.js, server/modules/user/use-cases/update-account.js
#164 
=======
---
---
---
- Project runs …
=> 164 general bugs

client/src/App.js, client/src/pages/Client/Signup/index.js, server/constants/app-links.js, server/modules/user/model/find.js, server/modules/user/model/update.js, server/modules/user/use-cases/client-signup.js
#174 
=======
---
---
---
- Project runs …
=> Fixes #174

client/src/components/Cards/Expandable/index.js, client/src/validation/err-msgs.js, client/src/validation/fields.js, server/modules/content/use-cases/create-content.js
#172 
=======
---
---
---
- Project runs …
=> 172 update cards bugs

client/src/api-calls/programmes.js, client/src/pages/Client/Feedback/index.js, client/src/pages/Therapist/AddClient/Step6.js, server/database/models/programmes-feedback/schema.sql, server/modules/programme/controllers/create-programme-feedback.js, server/modules/programme/controllers/index.js, server/modules/programme/model/create.js, server/modules/programme/use-cases/create-programme-feedback.js, server/modules/programme/use-cases/index.js
#79 
=======
---
---
---
- Project runs …
=> send feedback backend

package-lock.json, package.json, server/config/common.js, server/database/dummy-data-prod/build.js, server/database/dummy-data-prod/build.script.js, server/database/dummy-data-prod/index.js, server/database/dummy-data-prod/organisations.js, server/database/dummy-data-prod/users.js, server/modules/content/controllers/remove-content-from-programme.js, server/modules/content/controllers/remove-content-from-programme.spec.js, server/modules/content/model/find.js, server/modules/content/model/update.js, server/modules/content/use-cases/create-content.js, server/modules/content/use-cases/delete-content.js, server/modules/content/use-cases/get-library-content.js, server/modules/content/use-cases/remove-content-from-library.js, server/modules/content/use-cases/remove-content-from-programme.js, server/modules/programme/controllers/create-programme.spec.js, server/modules/programme/controllers/update-programme.spec.js, server/modules/programme/use-cases/create-programme.js, server/modules/programme/use-cases/manage-content-contents-categories.js, server/modules/programme/use-cases/update-programme.js, server/services/error-handler/sentry.js
=======
---
---
---
- Project runs …
=> Production db 2

client/package-lock.json, client/src/pages/Therapist/Library/index.js, server/modules/content/model/find.js, server/modules/content/use-cases/get-library-content.js
#180
=======
---
---
---
- Project runs …
=> fix admin no library content bug

client/src/App.js, client/src/pages/Therapist/ContactClient/index.js, client/src/pages/Therapist/index.js, client/src/validation/fields.js, server/modules/therapist-client/model/find.js
#192
=======
---
---
---
- Project runs …
=> Create contact client page

client/src/components/Inputs/BasicInput/index.js, client/src/components/Inputs/BasicInput/style.js, client/src/constants/content.js, client/src/pages/Client/MyTherapyGoals/index.js, client/src/pages/General/SuccessFeedback/index.js, client/src/pages/Therapist/AddClient/Step3.js, client/src/pages/Therapist/MyAccount/index.js, client/src/validation/fields.js, client/src/validation/schemas/account.js
#183 
=======
---
---
---
- Project runs …
=> 183 fix basic design bus

client/src/api-calls/media.js, client/src/components/Cards/Expandable/EditMode.js, client/src/components/Cards/Info/index.js, client/src/components/Cards/Info/style.js, client/src/components/Content/AddSingleContent/index.js, client/src/components/FileUpload/index.js, client/src/components/FileUpload/style.js, client/src/constants/content.js, client/src/pages/Therapist/CreateProgram/index.js, client/src/pages/Therapist/EditProgramme/Review.js, client/src/pages/Therapist/EditProgramme/index.js, server/modules/media/controllers/get-signed-url.js, server/modules/media/use-cases/get-signed-url.js, server/services/files-storage/config.js, server/services/files-storage/get-signed-url.js
#187
#186 
#190: I think that bugs 16,17 (notion) happened because we didn't allow uploads for .mov (quicktime) types as the standard iOS recording type so I've added this format now
20 should be resolved in #198
---
---
---
- Project runs
- Checked that …
=> upload bugfixes

client/src/helpers/cleanEmail.js, client/src/validation/fields.js
#205 
=======
---
---
---
- Project runs …
=> 205 fix validation on profile page

client/src/pages/Client/MyTherapyGoals/index.js, client/src/pages/Therapist/SingleClient/ClientHistory.js
Fixes #179 
Fixes #171 
Also realised we're not getting all of the goals (only first three) so have fixed that too
=======
---
---
---
- Project runs
- The new work has been checked with Axe …
=> Fix therapy goals 

client/src/components/Content/AddContentSection/index.js, client/src/pages/Therapist/CreateProgram/AddContent.js, server/constants/app-links.js, server/modules/content/use-cases/edit-content.js
#185 
#194 
#191
=======
---
---
---
- Project runs
- Code is consistent …
=> more bugfixes

client/src/pages/Therapist/AddClient/Step4.js, client/src/pages/Therapist/Library/index.js
#208 
#212
=======
---
---
---
- Project runs
- Code is consistent with …
=> 208 bugfix

client/src/pages/Client/MyAccount/index.js, client/src/validation/schemas/account.js, server/modules/user/model/find.js, server/modules/user/model/update.js, server/modules/user/use-cases/update-account.js
#220 
=======
---
---
---
- Project runs …
=> 220 add phone numbers to client account

client/src/components/Content/AddSingleContent/index.js, client/src/constants/content.js, client/src/pages/Client/Update/SendAudio.js, client/src/pages/Client/Update/SendVideo.js, server/services/files-storage/config.js
#216 
=======
---
---
---
- Project runs …
=> 216 bugfix

client/src/App.js, client/src/components/Layout/Onboarding/style.js, client/src/components/Route/index.js, client/src/helpers/ScrollToTop.js, client/src/helpers/index.js, client/src/pages/Client/MyTherapist/index.js, client/src/pages/Therapist/SingleClient/ClientHistory.js, client/src/pages/Therapist/SingleClient/index.js
#219
#217
#215
#214
#223 
=======
---
---
---
- Project runs
- Code is …
=> general bugs

client/package-lock.json, client/package.json, client/src/components/Cards/Expandable/ViewMode.js, client/src/components/Cards/Expandable/index.js, client/src/components/Navbar/NavRoutes.js, client/src/components/Video/index.js, client/src/index.js, client/src/pages/Therapist/SingleClient/index.js, server/modules/programme/use-cases/create-programme-feedback.js
Closes #231 
Closes #230 
=======
---
**To test analytics:**
- download the analytics extension: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna
- Go to index file and move react-ga initialisation outside of the production env condition
- Go to expandable index card and remove the production env condition
- Go to the video component and comment out the production env condition
- Go to view content and click to open a card 
In the console log if you filter for analytics you should see it log a new event. If you click either audio or video cards you'll also see it log an additional event to track that it was an audio piece …
=> Add Analytics and Remove Feedback

server/database/models/media/schema.sql
=======
---
---
---
- Project runs …
=> Increase character limit on file type

server/constants/content.js, server/constants/index.js, server/services/emails/templates/client.account-deleted.js, server/services/emails/templates/client.signup-invite.js, server/services/emails/templates/client.therapist-created-programme.js, server/services/emails/templates/client.therapist-respond-to-progress-update.js, server/services/emails/templates/client.therapist-updated-programme.js, server/services/emails/templates/therapist.client-account-deleted.js, server/services/emails/templates/therapist.client-sent-programme-feedback.js, server/services/emails/templates/therapist.client-sent-progress-update.js, server/services/emails/templates/user.reset-password.js
Closes #233 
=======
---
---
---
- Project runs
- Code is consistent with …
=> Add footer to emails > #233

client/src/components/Content/AddSingleContent/index.js, client/src/pages/Client/Update/SendAudio.js, client/src/pages/Client/Update/SendVideo.js
#238
=======
---
---
---
- Project runs …
=> removed to lower case

server/services/emails/templates/client.signup-invite.js, server/services/emails/templates/client.therapist-created-programme.js, server/services/emails/templates/client.therapist-respond-to-progress-update.js, server/services/emails/templates/client.therapist-updated-programme.js, server/services/emails/templates/therapist.client-sent-programme-feedback.js, server/services/emails/templates/therapist.client-sent-progress-update.js, server/services/emails/templates/user.reset-password.js
#229 
=======
---
---
---
- Project runs …
=> show links as plain text

server/database/migrations/20210427103924-on-delete-cascade-for-programme-contents.js, server/database/migrations/sqls/20210427103924-on-delete-cascade-for-programme-contents-down.sql, server/database/migrations/sqls/20210427103924-on-delete-cascade-for-programme-contents-up.sql, server/database/models/programmes-contents/schema.sql, server/modules/content/model/remove.js, server/modules/content/use-cases/delete-content.js
- add on delete cascade for programmes_contents table so it automatically delete the rows from the intermediate table 
=======
---
---
---
- Project runs
- The new work has been checked with Axe …
=> add on delete cascade hook for prog_contents

client/src/constants/nav-routes.js, client/src/pages/Client/Signup/index.js, client/src/pages/Therapist/Signup/index.js
#12 
=======
---
---
---
- Project runs …
=> added links and updated routing

client/src/constants/nav-routes.js, client/src/pages/General/Login/index.js, client/src/pages/Therapist/AddClient/Step6.js, client/src/pages/Therapist/AddClient/index.js, client/src/pages/Therapist/SingleClient/index.js, client/src/pages/Therapist/ViewUpdate/index.js, server/modules/progress-update/use-cases/get-progress-update-by-id.js, server/services/emails/templates/client.therapist-respond-to-progress-update.js
#247 #249 #248 
=======
---
---
---
- Project runs
- Code is consistent …
=> 247 248 249 bugs

client/package-lock.json, client/package.json, client/src/index.js
#252 
=======
---
---
---
- Project runs …
=> setup sentry for react

.vscode/settings.json, client/src/components/ReCaptcha/index.js, client/src/pages/Client/Signup/index.js, client/src/pages/General/Login/index.js, client/src/pages/Therapist/Signup/index.js, client/src/theme/global-style.js, package-lock.json, package.json, server/config/common.js, server/helpers/index.js, server/helpers/secondsToHms.js, server/modules/user/controllers/login.js, server/modules/user/use-cases/login.js, server/modules/user/utils/create-rate-limiter.js, server/modules/user/utils/index.js, server/services/error-handler/messages.js
#245 
=======
---
---
---
- Project runs …
=> 245 recaptcha

server/api/middlewares/helmet.js, server/api/middlewares/index.js, server/app.js
#264 
=======
---
---
---
- Project runs …
=> config csp in helmet middleware

.vscode/settings.json, client/src/App.js, client/src/api-calls/users.js, client/src/context/auth.js, client/src/pages/Client/MyAccount/index.js, package-lock.json, package.json, server/api/middlewares/csrf.js, server/api/middlewares/index.js, server/app.js, server/constants/common.js, server/modules/content/controllers/index.js, server/modules/content/controllers/remove-content-from-programme.js, server/modules/programme/controllers/index.js, server/modules/progress-update/controllers/index.js, server/modules/therapist-client/controllers/index.js, server/modules/user/controllers/get-csrf-token.js, server/modules/user/controllers/index.js
#263 
=======
---
---
---
- Project runs …
=> 263 csrf token
